vich_uploader:
    db_driver: orm
    mappings:
        course_thumbs:
            uri_prefix: /uploads/courses
            upload_destination: '%kernel.project_dir%/public/uploads/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_plans:
            uri_prefix: /uploads/course_plans
            upload_destination: '%kernel.project_dir%/public/uploads/course_plans'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer        
